name: Basic Workflow

on: 
  push:

jobs:
  
  tema-1_2:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Tema 1_2_ejem0
        run: mvn -B test --file Tema_1_2/tema1_2_ejem0/pom.xml
      # - name: Tema 1_2_ejem1
      #   run: mvn -B test --file Tema_1_2/tema1_2_ejem1/
      # - name: tema1_2_ejem2_assertj
      #   run: mvn -B test --file Tema_1_2/tema1_2_ejem2_assertj/
      - name: tema1_2_ejem3_mockito
        run: mvn -B test --file Tema_1_2/tema1_2_ejem3_mockito/pom.xml
      - name: tema1_2_ejem4_mockito
        run: mvn -B test --file Tema_1_2/tema1_2_ejem4_mockito/pom.xml
      - name: tema1_2_ejer1
        run: mvn -B test --file Tema_1_2/tema1_2_ejer1/pom.xml
      - name: tema1_2_ejer2
        run: mvn -B test --file Tema_1_2/tema1_2_ejer2/pom.xml
      - name: tema1_2_ejer3
        run: mvn -B test --file Tema_1_2/tema1_2_ejer3/pom.xml
      - name: tema1_2_ejer4
        run: mvn -B test --file Tema_1_2/tema1_2_ejer4/pom.xml
      - name: tema1_2_ejer5
        run: mvn -B test --file Tema_1_2/tema1_2_ejer5/pom.xml
      - name: tema1_2_ejer6
        run: mvn -B test --file Tema_1_2/tema1_2_ejer6/pom.xml
      - name: tema1_2_ejer7
        run: mvn -B test --file Tema_1_2/tema1_2_ejer7/pom.xml
      - name: tema1_2_ejer8
        run: mvn -B test --file Tema_1_2/tema1_2_ejer8/pom.xml
      - name: tema1_2_ejer9
        run: mvn -B test --file Tema_1_2/tema1_2_ejer9/pom.xml
      - name: tema1_2_ejer9-solucion
        run: mvn -B test --file Tema_1_2/tema1_2_ejer9-solucion/pom.xml

  # tema-1_4:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 11
  #     - name: selenium_ejem1
  #       run: mvn -B test --file Tema_1_4/selenium_ejem1/
  #     - name: selenium_ejem2
  #       run: mvn -B test --file Tema_1_4/selenium_ejem2/
  #     - name: selenium_ejer1
  #       run: mvn -B test --file Tema_1_4/selenium_ejer1/
  #     - name: selenium_ejer1_enunciado
  #       run: mvn -B test --file Tema_1_4/selenium_ejer1_enunciado/

  tema-1_6:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: rest_test_ejem1
        run: mvn -B test --file Tema_1_6/rest_test_ejem1/pom.xml
      - name: rest_test_ejem2
        run: mvn -B test --file Tema_1_6/rest_test_ejem2/pom.xml
      - name: rest_test_ejer1
        run: mvn -B test --file Tema_1_6/rest_test_ejer1/pom.xml